version: "3.7"

services:
  redis:
    image: redis:7.2.3
    ports:
      - "6379:6379"
  prometheus:
    build:
      context: ../..
      dockerfile: deploy/docker/Dockerfile.prometheus
    ports:
      - "9090:9090"
    volumes:
      - prom:/prometheus
  grafana:
    image: grafana/grafana-oss:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana:/var/lib/grafana
  mysql:
    build:
      context: ../..
      dockerfile: deploy/docker/Dockerfile.mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql:/var/lib/mysq
  etcd:
    image: quay.io/coreos/etcd:v3.4.15
    command:
      - etcd
      - --data-dir
      - /data.etcd
      - --name
      - occa-1
      - --advertise-client-urls
      - http://0.0.0.0:2379
      - --listen-client-urls
      - http://0.0.0.0:2379
      - --listen-peer-urls
      - http://0.0.0.0:2380
    ports:
      - "2379:2379"
      - "2380:2380"
    volumes:
      - etcd:/data.etcd
volumes:
  prom:
  grafana:
  mysql:
  etcd: