serverID: ${SERVER_ID:"event_server"}

logger:
  level: info
  component: event-server

httpListenAddress: 0.0.0.0:${HTTP_LISTEN_ADDRESS:9001}
grpcListenAddress: localhost:${GRPC_LISTEN_ADDRESS:9002}

memstore:
  address: localhost:6379

auth:
  type: jwtRSA
  jwt:
    publicKeyPath: ./tmp/keys/occa_pub

etcd:
  endpoints:
    - http://localhost:2379