logger:
  level: info
  component: gateway

listenAddress: 0.0.0.0:9000

inMemoryDB:
  address: localhost:6379

auth:
  type: jwtRSA
  jwt:
    publicKeyPath: ./tmp/keys/occa_pub

registerer:
  jwt:
    privateKeyPath: ./tmp/keys/occa
  database:
    dbType: mysql
    host: localhost
    port: 3306
    database: auth
    username: root
    password: root
